//*************************************************************************
// Copyright (C) Security Innovation, LLC, 2002-2003 – All Rights Reserved.
//
// FILE:		defines.h
//
// DESCRIPTION: Contains common defines for Holodeck used in multiple modules
//
//=========================================================================
// Modification History
//
// Date         SCR  Name        Purpose
// -----------  ---  ----------- ------------------------------------------
// 30 DEC 2002		 B. Shirey	 File created.
//*************************************************************************
#pragma once

#define MAX_TRIAL_LOG_ENTRIES		100
#define ROOT_KEY					HKEY_LOCAL_MACHINE
#define INSTALLED_ROOT_KEY			HKEY_LOCAL_MACHINE
#define ROOT_PATH					"Software\\HolodeckEE"
#define DOTNET_REPLACEMENT_DLLS_KEY	"DotNetReplacementDlls"
#define LOG_VERSION_STRING			"HDV2_5"
#define LOG_PIPE_VALUE_NAME			"LogPipeName"
#define TEST_SETTINGS_KEY			"TestSettings"
#define DISABLE_LOGGING_KEY			"Disabled Logging List"
#define DISABLE_LOGGING_VALUE		"DisableAll"
#define INSTALL_PATH_VALUE_NAME		"InstallPath"
#define PANE_SETTINGS_VALUE_NAME	"PaneSettings"
#define PANE_VISIBLE_VALUE_NAME		"Displayed"
#define SERIAL_NUMBER_VALUE_NAME	"SerialNumber"
#define REGISTRATION_KEY_VALUE_NAME	"RegistrationKey"
#define FUNCTION_DB_PATH_VALUE_NAME	"FunctionDatabaseFolder"
#define TOOLS_PATH_VALUE_NAME		"ToolsFolder"
#define LIB_EXPORT_PATH_VALUE_NAME	"LibraryExportPath"
#define NEWINTERCEPTS_TPL_PATH_NAME "NewInterceptsTemplatePath"
#define PLUGIN_DLL_PATH_VALUE_NAME	"ReplacementLibraryFolder"
#define LOG_PATH_VALUE_NAME			"LogFolder"
#define DOT_NET_CACHE_PATH_VALUE	"DotNetCacheFolder"
#define DTD_PATH_VALUE_NAME			"DtdPath"
#define PROCESS_CHAINING_VALUE_NAME	"ProcessChaining"
#define USAGE_REG_KEY_NAME			"Usage"
#define FUNCTION_CALL_COUNT_VALUE_NAME	"CallCount"
#define MAX_DISK_USAGE_VALUE_NAME	"MaxDiskUsage"
#define CURR_DISK_USAGE_VALUE_NAME	"CurrentDiskUsage"
#define MAX_MEM_USAGE_VALUE_NAME	"MaxMemoryUsage"
#define CURR_MEM_USAGE_VALUE_NAME	"CurrentMemoryUsage"
#define NETWORK_ULOADBW_VALUE_NAME  "UploadBandwidth"
#define NETWORK_DLOADBW_VALUE_NAME  "DownloadBandwidth"
#define TOTAL_BYTES_SENT_VALUE_NAME "TotalBytesSent"
#define TOTAL_BYTES_RECV_VALUE_NAME "TotalBytesReceived"
#define NETWORK_RECVSTMP_VALUE_NAME "NetworkLastReceiveStamp"
#define NETWORK_SENDSTMP_VALUE_NAME "NetworkLastSendStamp"
#define CHECK_RESOURCE_PARAM_VALUE_NAME		"ParamIndex"
#define CHECK_RESOURCE_EXISTS_VALUE_NAME	"Exists"
#define FAULTS_KEY_NAME				"Faults"
#define RETURN_VALUE_KEY_NAME		"ReturnValue"
#define ERROR_CODE_KEY_NAME			"ErrorCode"
#define EXCEPTION_KEY_NAME			"Exception"
#define ALLOCATION_KEY_NAME			"Allocation"
#define PASSTHROUGH_KEY_NAME		"PassThrough"
#define PASSTHROUGH_RETURN_VALUE_KEY_NAME	"PassThroughReturnValue"
#define PASSTHROUGH_ERROR_CODE_KEY_NAME		"PassThroughErrorCode"
#define CHECK_RESOURCE_KEY_NAME		"CheckResource"
#define PANES_KEY_NAME				"Panes"
#define MATCH_PARAMS_KEY_NAME		"MatchParams"
#define CHANGE_PARAMS_KEY_NAME		"ChangeParams"
#define TEST_FIRE_DETAILS__KEY_NAME	"FiringDetails"
#define FIRING_OPTION_VALUE_NAME	"FiringOption"
#define FIRING_PAUSE_APP_VALUE_NAME	"PauseAppOnTestFire"
#define FIRING_DATALIST_KEY_NAME	"FiringData"
#define PARAM_TYPE_VALUE_NAME		"ParamType"
#define PARAM_OPERATOR_VALUE_NAME	"ParamOperatorType"
#define PARAM_VALUE_VALUE_NAME		"ParamValue"
#define ERROR_CODE_VALUE_NAME		"ErrorCode"
#define RETURN_VALUE_VALUE_NAME		"ReturnValue"
#define FUNCTION_DB_FILE_NAME		"functions.xml"
#define DOT_NET_FUNC_DB_FILE_NAME	"DotNetFunctions.xml"
#define FAULT_DB_FILE_NAME			"faults.xml"
#define ERROR_CODE_DB_FILE_NAME		"ErrorCodes.xml"
#define EXCEPTION_DB_FILE_NAME		"Exceptions.xml"
#define PORT_DB_FILE_NAME			"Ports.xml"
#define SEND_LOG_WAIT_TIME			100
#define RECEIVE_LOG_WAIT_TIME		2000
#define LOG_SENT_EVENT_NAME_PREFIX	"HolodeckLogsSent_"
#define NOTIFIER_DONE_EVENT_PREFIX	"HolodeckLogsReceived_"
#define LOG_SENT_MAP_FILE_PREFIX	"HolodeckMMFile_"
#define LOG_FILE_MUTEX_PREFIX		"HolodeckLogAccess_"
#define CHILD_PROCESS_EVENT_PREFIX	"HolodeckChildProcCreated_"
#define HOLODECK_ATTACHED_PREFIX	"HolodeckAttachedToNewChild_"
#define CHILD_PROC_MAP_FILE_PREFIX	"HolodeckChildProcDataFile_"
#define FORCE_WRITE_MUTEX_PREFIX	"HolodeckLogWrite_"
#define HEAT_INJECT_DONE_PREFIX		"HEATInjectionDone_"
#define LOG_TRUE_DISPLAY_STRING		"True"
#define LOG_FALSE_DISPLAY_STRING	"False"
#define HEAT_DLL_FILE_NAME			"Heat4Dll.dll"
#define FILE_CORRUPTION_EXE_FILE	"FileCorruptionGenerator.exe"
#define LIBRARY_WRAPPER_EXE_FILE	"LibraryExport.exe"
#define DISABLE_INTERCEPT_FUNC_NAME	"disableInterceptionInCurrentThread"
#define ENABLE_INTERCEPT_FUNC_NAME	"enableInterceptionInCurrentThread"
#define GET_CALL_LEVEL_FUNC_NAME	"getCallLevel"
#define INC_CALL_LEVEL_FUNC_NAME	"incrementCallLevel"
#define DEC_CALL_LEVEL_FUNC_NAME	"decrementCallLevel"
#define ORIGINAL_CALLER_FUNC_NAME	"getOriginalFunctionCaller"
// 60 seconds in 1 millisecond intervals
#define WAIT_FOR_SERVICE_TIMEOUT	60000
#define SERVICE_GROUP_KEY_NAME		"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\SvcHost"
#define SERVICES_BASE_KEY_NAME		"SYSTEM\\CurrentControlSet\\Services"
#define IMAGE_PATH_VALUE_NAME		"ImagePath"
#define MAX_PARAMETER_COLUMNS		12
#define MAX_VISIBLE_LOG_ENTRIES		100
#define LOG_FOLDER_DEFAULT_VALUE	"\\Logs"
#define REPORT_FOLDER_DEFAULT_VALUE	"\\Reports"
#define REPORT_FILE_NAME			"Holodeck Report.htm"
#define LOGS_XML_FILE_NAME			"\\Holodeck Report_files\\Logs.xml"
#define FAULTS_XML_FILE_NAME		"\\Holodeck Report_files\\Faults.xml"
#define TESTS_XML_FILE_NAME			"\\Holodeck Report_files\\Tests.xml"
#define PARAMS_XML_FILE_NAME		"\\Holodeck Report_files\\Param Values.xml"
#define RESOURCES_XML_FILE_NAME		"\\Holodeck Report_files\\Resource Dependencies.xml"
#define ICON_FILE_NAME				"images\\app.ico"
#define GLOBAL_THREAD_NAME			"Common"
#define RECORDED_SESSION_FOLDER		"\\Recorded Sessions"
#define RECORDED_SESSION_FILE		"\\Recorded Session.xml"
#define TESTGEN_SETTINGS_FILE       "\\Test Generation\\StressTestGeneration.xml"
#define ERROR_LOG_FILE				"ErrorLog.txt"
#define NET_CORRUPT_KEY_NAME		"NetworkCorruption"
#define NET_CORRUPT_RECV_VALUE		"Recv"
#define NET_CORRUPT_SEND_VALUE		"Send"
#define NET_CORRUPT_PORT_MASK		"PortMask"
#define NET_CORRUPT_MODIFY_EXPR		"Expr"
#define FILE_CORRUPT_KEY_NAME		"FileCorruption"
#define FILE_CORRUPT_ORIG_FILE		"OrigFile"
#define FILE_CORRUPT_REGEN_VALUE	"Regen"
#define FILE_CORRUPT_MODIFY_EXPR	"Expr"
#define FILE_CORRUPT_LAST_FILE		"LastCorruptedFile"
#define FILE_CORRUPT_LAST_CHANGES	"LastCorruptedChanges"
#define REGISTRY_CHANGE_WAIT_TIME	100
#define PROJECT_PATH_VALUE_NAME		"ProjectPath"

//button bar icons
#define NEW_PROJECT_ICON_FILE		"images\\new_project.gif"
#define OPEN_PROJECT_ICON_FILE		"images\\open_project.gif"
#define SAVE_PROJECT_ICON_FILE		"images\\save_project.gif"
#define NEW_TEST_APP_ICON_FILE		"images\\new_test_app.gif"
#define CREATE_TEST_ICON_FILE		"images\\create_test.gif"
#define NEW_FAULT_ICON_FILE			"images\\new_fault.gif"
#define CREATE_REPORT_ICON_FILE		"images\\create_report.gif"
#define PROJECT_PANE_ICON_FILE		"images\\project_pane.gif"
#define RESOURCE_PANE_ICON_FILE		"images\\resource_pane.gif"
#define LIMITS_PANE_ICON_FILE		"images\\limits_pane.gif"
#define PROPERTIES_PANE_ICON_FILE	"images\\properties_pane.gif"
#define HELP_CONTENTS_ICON_FILE		"images\\help_contents_pane.gif"
#define DYNAMIC_HELP_ICON_FILE		"images\\help_pane.gif"
#define HOLODECK_LOGO_FILE			"images\\HolodeckEE.bmp"
//project pane icons
#define PROCESS_ICON_FILE			"images\\Process.ico"
#define THREAD_ICON_FILE			"images\\Thread.ico"
#define RECORDEDSESSIONS_ICON_FILE	"images\\RecordedSessions.ico"
#define RECORDEDSESSION_ICON_FILE	"images\\RecordedSession.ico"
#define REPORTS_ICON_FILE			"images\\Reports.ico"
#define REPORT_ICON_FILE			"images\\Report.ico"
#define LOGS_ICON_FILE				"images\\Logs.ico"
#define ACTIVELOG_ICON_FILE			"images\\ActiveLog.ico"
#define SAVEDLOG_ICON_FILE			"images\\SavedLog.ico"
#define RESOURCES_ICON_FILE			"images\\Resources.ico"
#define MEMORY_ICON_FILE			"images\\Memory.ico"
#define DISK_ICON_FILE				"images\\Disk.ico"
#define NETWORK_ICON_FILE			"images\\Network.ico"
#define FILES_ICON_FILE				"images\\Files.ico"
#define FILE_ICON_FILE				"images\\File.ico"
#define REGISTRY_ICON_FILE			"images\\Registry.ico"
#define REGISTRYENTRY_ICON_FILE		"images\\RegistryEntry.ico"
#define FAULTS_ICON_FILE			"images\\Faults.ico"
#define FAULT_ICON_FILE				"images\\Fault.ico"
#define LIMITS_ICON_FILE			"images\\Limits.ico"
#define TESTS_ICON_FILE				"images\\Tests.ico"
#define TEST_ICON_FILE				"images\\Test.ico"
// dynamic help pages
#define BLANK_HTML_FILE				"about:blank"
#define LOGS_DYNAMIC_HELP_FILE		"help\\logpane_dyn.html"
#define FAULTS_DYNAMIC_HELP_FILE	"help\\faultpane_dyn.html"
#define RESOURCES_DYNAMIC_HELP_FILE	"help\\resourcepane_dyn.html"
#define TESTS_DYNAMIC_HELP_FILE		"help\\testspane_dyn.html"
#define PROCESS_DYNAMIC_HELP_FILE	"help\\process_dyn.html"
#define THREAD_DYNAMIC_HELP_FILE	"help\\thread_dyn.html"
#define REPORTS_DYNAMIC_HELP_FILE	"help\\reports_dyn.html"
#define RECORDED_DYNAMIC_HELP_FILE	"help\\recorded_dyn.html"
#define LIMITS_DYNAMIC_HELP_FILE	"help\\limits_dyn.html"
#define NETWORK_DYNAMIC_HELP_FILE	"help\\network_dyn.html"
#define TABLE_OF_CONTENTS_HELP_FILE	"help\\holodeck_help.htm"
// trial disabled help pages
#define FILE_CORRUPTION_HELP_FILE	"help\\holodeck_fundamentals\\using_holodeck_to_test_network_protocols_and_network_based_security\\using_holodeck_to_corrupt_files_and_test_file_processing.htm"
#define LIBRARY_EXPORTER_HELP_FILE	"help\\customizing_and_extending_holodeck\\using_the_custom_intercept_generator\\getting_started_with_the_library_exporter.htm"
#define NEW_TEST_APP_HELP_FILE		"help\\holodeck_fundamentals\\dealing_with_multiple_processes.htm"
#define EXPORT_LOG_HELP_FILE		"help\\working_with_log_files\\saving_log_files.htm"
#define CODE_COVERAGE_HELP_FILE		"help\\holodeck_fundamentals\\automatic_test_generation\\using_holodeck_for_code_coverage_test_generation.htm"
#define STRESS_TEST_HELP_FILE		"help\\holodeck_fundamentals\\automatic_test_generation\\using_holodeck_for_stress_test_generation.htm"
#define RECORD_SESSION_HELP_FILE	"help\\holodeck_fundamentals\\recording_and_replaying.htm"
#define REPLAY_SESSION_HELP_FILE	"help\\holodeck_fundamentals\\recording_and_replaying.htm"
// other help pages used in HD
#define GETTING_STARTED_HELP_FILE	"help\\getting_started_with_holodeck\\getting_started_with_holodeck.htm"
#define NAG_SCREEN_HELP_FILE		"purchase.htm"
// custom filter forms
#define MAX_DISPLAY_ERRORCODES		500
#define MAX_DISPLAY_RETURNVALS		500
// create scheduled test wizard
#define OUT_PARAM_NO_CHANGE_STRING	"No Change"
#define IN_PARAM_MATCH_ANY_STRING	"{Any}"
#define EQUAL_OPERATOR_TEXT			"Equal To"
#define EQUAL_OPERATOR				"="
#define NOT_EQUAL_OPERATOR_TEXT		"Not Equal To"
#define NOT_EQUAL_OPERATOR			"!="
#define LESS_THAN_OPERATOR_TEXT		"Less Than"
#define LESS_THAN_OPERATOR			"<"
#define GREATER_THAN_OPERATOR_TEXT	"Greater Than"
#define GREATER_THAN_OPERATOR		">"
#define LESS_EQUAL_OPERATOR_TEXT	"Less Than Or Equal To"
#define LESS_EQUAL_OPERATOR			"<="
#define GREATER_EQUAL_OPERATOR_TEXT	"Greater Than Or Equal To"
#define GREATER_EQUAL_OPERATOR		">="
#define STARTS_WITH_OPERATOR_TEXT	"Starts With"
#define STARTS_WITH_OPERATOR		"starts with"
#define ENDS_WITH_OPERATOR_TEXT		"Ends With"
#define ENDS_WITH_OPERATOR			"ends with"
#define SUBSTRING_OPERATOR_TEXT		"Contains Substring"
#define SUBSTRING_OPERATOR			"contains"
#define NOT_CONTAINS_OPERATOR_TEXT	"Doesn't Contain Substring"
#define NOT_CONTAINS_OPERATOR		"not contains"
#define BINARY_CONTAINS_OPERATOR_TEXT		"Contains Binary Value"
#define BINARY_CONTAINS_OPERATOR			"binary contains"
#define BINARY_NOT_CONTAINS_OPERATOR_TEXT	"Doesn't Contain Binary Value"
#define BINARY_NOT_CONTAINS_OPERATOR		"binary not contains"
#define EQUAL_RESOURCE_OPERATOR_TEXT		"Equal to resource path"
#define EQUAL_RESOURCE_OPERATOR				"=resource"
#define NOT_EQUAL_RESOURCE_OPERATOR_TEXT	"Not equal to resource path"
#define NOT_EQUAL_RESOURCE_OPERATOR			"!=resource"
#define CONTAINS_RESOURCE_OPERATOR_TEXT		"Contains resource path"
#define CONTAINS_RESOURCE_OPERATOR			"contains resource"
#define NOT_CONTAINS_RESOURCE_OPERATOR_TEXT	"Doesn't contain resource path"
#define NOT_CONTAINS_RESOURCE_OPERATOR		"not contains resource path"

// column header text
#define TIME_STAMP_HEADER_TEXT		"TimeStamp"
#define THREAD_ID_HEADER_TEXT		"Thread"
#define CATEGORY_HEADER_TEXT		"Category"
#define DLL_HEADER_TEXT				"Dll"
#define FUNCTION_HEADER_TEXT		"Function"
#define RETURN_VALUE_HEADER_TEXT	"Return Value"
#define ERROR_CODE_HEADER_TEXT		"Error Code"
#define EXCEPTION_HEADER_TEXT		"Exception"
#define PARAM_HEADER_TEXT_PREFIX	"Parameter "
// corruption fault strings
#define RANDOM_CORRUPTION_TEXT		"Random"
#define REG_EXPR_CORRUPTION_TEXT	"RegExpr"
#define REPLACE_CORRUPTION_TEXT		"Replace"
#define RANDOM_SINGLE_BYTE_TEXT		"Random Single Byte"
