//*************************************************************************
// Copyright (C) Security Innovation, LLC, 2002-2004  All Rights Reserved.
//
// FILE:		Kernel32ReplacementLibrary.h
//
// DESCRIPTION: Contains replacement library prototypes for kernel32.dll
//
//=========================================================================
// Modification History
//
// Generated 05/05/2004 05:32:00 PM
//*************************************************************************
#pragma once

#define _WIN32_WINNT 0x0501

#include <windows.h>
#include "Registry.h"
#include "ReplacementLibrary.h"
#include "Log.h"

using namespace Replacement;
using namespace Log;

// function pointer definitions
typedef WINBASEAPI BOOL (WINAPI *AllocateUserPhysicalPagesFunction)(HANDLE, PULONG_PTR, PULONG_PTR);
typedef WINBASEAPI BOOL (WINAPI *CopyFileAFunction)(LPCSTR, LPCSTR, BOOL);
typedef WINBASEAPI BOOL (WINAPI *CopyFileExAFunction)(LPCSTR, LPCSTR, LPPROGRESS_ROUTINE, LPVOID, LPBOOL, DWORD);
typedef WINBASEAPI BOOL (WINAPI *CopyFileExWFunction)(LPCWSTR, LPCWSTR, LPPROGRESS_ROUTINE, LPVOID, LPBOOL, DWORD);
typedef WINBASEAPI BOOL (WINAPI *CopyFileWFunction)(LPCWSTR, LPCWSTR, BOOL);
typedef WINBASEAPI BOOL (WINAPI *CreateDirectoryAFunction)(LPCSTR, LPSECURITY_ATTRIBUTES);
typedef WINBASEAPI BOOL (WINAPI *CreateDirectoryExAFunction)(LPCSTR, LPCSTR, LPSECURITY_ATTRIBUTES);
typedef WINBASEAPI BOOL (WINAPI *CreateDirectoryExWFunction)(LPCWSTR, LPCWSTR, LPSECURITY_ATTRIBUTES);
typedef WINBASEAPI BOOL (WINAPI *CreateDirectoryWFunction)(LPCWSTR, LPSECURITY_ATTRIBUTES);
typedef WINBASEAPI HANDLE (WINAPI *CreateFileAFunction)(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
typedef WINBASEAPI HANDLE (WINAPI *CreateFileWFunction)(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
typedef WINBASEAPI BOOL (WINAPI *CreateProcessAFunction)(LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION);
typedef WINBASEAPI BOOL (WINAPI *CreateProcessWFunction)(LPCWSTR, LPWSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION);
typedef WINBASEAPI BOOL (WINAPI *DeleteFileAFunction)(LPCSTR);
typedef WINBASEAPI BOOL (WINAPI *DeleteFileWFunction)(LPCWSTR);
typedef WINBASEAPI BOOL (WINAPI *FlushFileBuffersFunction)(HANDLE);
typedef WINBASEAPI BOOL (WINAPI *FreeLibraryFunction)(HMODULE);
typedef WINBASEAPI VOID (WINAPI *FreeLibraryAndExitThreadFunction)(HMODULE, DWORD);
typedef WINBASEAPI BOOL (WINAPI *FreeUserPhysicalPagesFunction)(HANDLE, PULONG_PTR, PULONG_PTR);
typedef WINBASEAPI BOOL (WINAPI *GetBinaryTypeAFunction)(LPCSTR, LPDWORD);
typedef WINBASEAPI BOOL (WINAPI *GetBinaryTypeWFunction)(LPCWSTR, LPDWORD);
typedef WINBASEAPI DWORD (WINAPI *GetCurrentDirectoryAFunction)(DWORD, LPSTR);
typedef WINBASEAPI DWORD (WINAPI *GetCurrentDirectoryWFunction)(DWORD, LPWSTR);
typedef WINBASEAPI BOOL (WINAPI *GetDiskFreeSpaceAFunction)(LPCSTR, LPDWORD, LPDWORD, LPDWORD, LPDWORD);
typedef WINBASEAPI BOOL (WINAPI *GetDiskFreeSpaceExAFunction)(LPCSTR, PULARGE_INTEGER, PULARGE_INTEGER, PULARGE_INTEGER);
typedef WINBASEAPI BOOL (WINAPI *GetDiskFreeSpaceExWFunction)(LPCWSTR, PULARGE_INTEGER, PULARGE_INTEGER, PULARGE_INTEGER);
typedef WINBASEAPI BOOL (WINAPI *GetDiskFreeSpaceWFunction)(LPCWSTR, LPDWORD, LPDWORD, LPDWORD, LPDWORD);
typedef WINBASEAPI UINT (WINAPI *GetDriveTypeAFunction)(LPCSTR);
typedef WINBASEAPI UINT (WINAPI *GetDriveTypeWFunction)(LPCWSTR);
typedef WINBASEAPI DWORD (WINAPI *GetFileAttributesAFunction)(LPCSTR);
typedef WINBASEAPI BOOL (WINAPI *GetFileAttributesExAFunction)(LPCSTR, GET_FILEEX_INFO_LEVELS, LPVOID);
typedef WINBASEAPI BOOL (WINAPI *GetFileAttributesExWFunction)(LPCWSTR, GET_FILEEX_INFO_LEVELS, LPVOID);
typedef WINBASEAPI DWORD (WINAPI *GetFileAttributesWFunction)(LPCWSTR);
typedef WINBASEAPI BOOL (WINAPI *GetFileInformationByHandleFunction)(HANDLE, LPBY_HANDLE_FILE_INFORMATION);
typedef WINBASEAPI DWORD (WINAPI *GetFileSizeFunction)(HANDLE, LPDWORD);
typedef WINBASEAPI BOOL (WINAPI *GetFileSizeExFunction)(HANDLE, PLARGE_INTEGER);
typedef WINBASEAPI DWORD (WINAPI *GetFileTypeFunction)(HANDLE);
typedef WINBASEAPI DWORD (WINAPI *GetLogicalDrivesFunction)();
typedef WINBASEAPI DWORD (WINAPI *GetLogicalDriveStringsAFunction)(DWORD, LPSTR);
typedef WINBASEAPI DWORD (WINAPI *GetLogicalDriveStringsWFunction)(DWORD, LPWSTR);
typedef WINBASEAPI HGLOBAL (WINAPI *GlobalAllocFunction)(UINT, SIZE_T);
typedef WINBASEAPI HGLOBAL (WINAPI *GlobalFreeFunction)(HGLOBAL);
typedef WINBASEAPI BOOL (WINAPI *GlobalMemoryStatusExFunction)(LPMEMORYSTATUSEX);
typedef WINBASEAPI LPVOID (WINAPI *HeapAllocFunction)(HANDLE, DWORD, SIZE_T);
typedef WINBASEAPI SIZE_T (WINAPI *HeapCompactFunction)(HANDLE, DWORD);
typedef WINBASEAPI HANDLE (WINAPI *HeapCreateFunction)(DWORD, SIZE_T, SIZE_T);
typedef WINBASEAPI BOOL (WINAPI *HeapDestroyFunction)(HANDLE);
typedef WINBASEAPI BOOL (WINAPI *HeapFreeFunction)(HANDLE, DWORD, LPVOID);
typedef WINBASEAPI BOOL (WINAPI *HeapLockFunction)(HANDLE);
typedef WINBASEAPI LPVOID (WINAPI *HeapReAllocFunction)(HANDLE, DWORD, LPVOID, SIZE_T);
typedef WINBASEAPI SIZE_T (WINAPI *HeapSizeFunction)(HANDLE, DWORD, LPCVOID);
typedef WINBASEAPI BOOL (WINAPI *HeapUnlockFunction)(HANDLE);
typedef WINBASEAPI BOOL (WINAPI *HeapValidateFunction)(HANDLE, DWORD, LPCVOID);
typedef WINBASEAPI HMODULE (WINAPI *LoadLibraryAFunction)(LPCSTR);
typedef WINBASEAPI HMODULE (WINAPI *LoadLibraryExAFunction)(LPCSTR, HANDLE, DWORD);
typedef WINBASEAPI HMODULE (WINAPI *LoadLibraryExWFunction)(LPCWSTR, HANDLE, DWORD);
typedef WINBASEAPI HMODULE (WINAPI *LoadLibraryWFunction)(LPCWSTR);
typedef WINBASEAPI HLOCAL (WINAPI *LocalAllocFunction)(UINT, SIZE_T);
typedef WINBASEAPI HLOCAL (WINAPI *LocalFreeFunction)(HLOCAL);
typedef WINBASEAPI HLOCAL (WINAPI *LocalReAllocFunction)(HLOCAL, SIZE_T, UINT);
typedef WINBASEAPI BOOL (WINAPI *MapUserPhysicalPagesFunction)(PVOID, ULONG_PTR, PULONG_PTR);
typedef WINBASEAPI BOOL (WINAPI *MapUserPhysicalPagesScatterFunction)(PVOID *, ULONG_PTR, PULONG_PTR);
typedef WINBASEAPI LPVOID (WINAPI *MapViewOfFileFunction)(HANDLE, DWORD, DWORD, DWORD, SIZE_T);
typedef WINBASEAPI LPVOID (WINAPI *MapViewOfFileExFunction)(HANDLE, DWORD, DWORD, DWORD, SIZE_T, LPVOID);
typedef WINBASEAPI BOOL (WINAPI *MoveFileAFunction)(LPCSTR, LPCSTR);
typedef WINBASEAPI BOOL (WINAPI *MoveFileExAFunction)(LPCSTR, LPCSTR, DWORD);
typedef WINBASEAPI BOOL (WINAPI *MoveFileExWFunction)(LPCWSTR, LPCWSTR, DWORD);
typedef WINBASEAPI BOOL (WINAPI *MoveFileWFunction)(LPCWSTR, LPCWSTR);
typedef WINBASEAPI BOOL (WINAPI *MoveFileWithProgressAFunction)(LPCSTR, LPCSTR, LPPROGRESS_ROUTINE, LPVOID, DWORD);
typedef WINBASEAPI BOOL (WINAPI *MoveFileWithProgressWFunction)(LPCWSTR, LPCWSTR, LPPROGRESS_ROUTINE, LPVOID, DWORD);
typedef WINBASEAPI BOOL (WINAPI *ReadFileFunction)(HANDLE, LPVOID, DWORD, LPDWORD, LPOVERLAPPED);
typedef WINBASEAPI BOOL (WINAPI *ReadFileExFunction)(HANDLE, LPVOID, DWORD, LPOVERLAPPED, LPOVERLAPPED_COMPLETION_ROUTINE);
typedef WINBASEAPI BOOL (WINAPI *ReadFileScatterFunction)(HANDLE, FILE_SEGMENT_ELEMENT[], DWORD, LPDWORD, LPOVERLAPPED);
typedef WINBASEAPI BOOL (WINAPI *RemoveDirectoryAFunction)(LPCSTR);
typedef WINBASEAPI BOOL (WINAPI *RemoveDirectoryWFunction)(LPCWSTR);
typedef WINBASEAPI BOOL (WINAPI *ReplaceFileAFunction)(LPCSTR, LPCSTR, LPCSTR, DWORD, LPVOID, LPVOID);
typedef WINBASEAPI BOOL (WINAPI *ReplaceFileWFunction)(LPCWSTR, LPCWSTR, LPCWSTR, DWORD, LPVOID, LPVOID);
typedef WINBASEAPI DWORD (WINAPI *SearchPathAFunction)(LPCSTR, LPCSTR, LPCSTR, DWORD, LPSTR, LPSTR *);
typedef WINBASEAPI DWORD (WINAPI *SearchPathWFunction)(LPCWSTR, LPCWSTR, LPCWSTR, DWORD, LPWSTR, LPWSTR *);
typedef WINBASEAPI BOOL (WINAPI *SetFileAttributesAFunction)(LPCSTR, DWORD);
typedef WINBASEAPI BOOL (WINAPI *SetFileAttributesWFunction)(LPCWSTR, DWORD);
typedef WINBASEAPI LPVOID (WINAPI *VirtualAllocFunction)(LPVOID, SIZE_T, DWORD, DWORD);
typedef WINBASEAPI LPVOID (WINAPI *VirtualAllocExFunction)(HANDLE, LPVOID, SIZE_T, DWORD, DWORD);
typedef WINBASEAPI BOOL (WINAPI *VirtualFreeFunction)(LPVOID, SIZE_T, DWORD);
typedef WINBASEAPI BOOL (WINAPI *VirtualFreeExFunction)(HANDLE, LPVOID, SIZE_T, DWORD);
typedef WINBASEAPI BOOL (WINAPI *VirtualLockFunction)(LPVOID, SIZE_T);
typedef WINBASEAPI SIZE_T (WINAPI *VirtualQueryFunction)(LPCVOID, PMEMORY_BASIC_INFORMATION, SIZE_T);
typedef WINBASEAPI SIZE_T (WINAPI *VirtualQueryExFunction)(HANDLE, LPCVOID, PMEMORY_BASIC_INFORMATION, SIZE_T);
typedef WINBASEAPI BOOL (WINAPI *VirtualUnlockFunction)(LPVOID, SIZE_T);
typedef WINBASEAPI BOOL (WINAPI *WriteFileFunction)(HANDLE, LPCVOID, DWORD, LPDWORD, LPOVERLAPPED);
typedef WINBASEAPI BOOL (WINAPI *WriteFileExFunction)(HANDLE, LPCVOID, DWORD, LPOVERLAPPED, LPOVERLAPPED_COMPLETION_ROUTINE);
typedef WINBASEAPI BOOL (WINAPI *WriteFileGatherFunction)(HANDLE, FILE_SEGMENT_ELEMENT[], DWORD, LPDWORD, LPOVERLAPPED);
typedef WINBASEAPI BOOL (WINAPI *AllocConsoleFunction)();
typedef WINBASEAPI BOOL (WINAPI *AreFileApisANSIFunction)();
typedef WINBASEAPI BOOL (WINAPI *AttachConsoleFunction)(DWORD);
typedef WINBASEAPI BOOL (WINAPI *BackupReadFunction)(HANDLE, LPBYTE, DWORD, LPDWORD, BOOL, BOOL, LPVOID *);
typedef WINBASEAPI BOOL (WINAPI *BackupSeekFunction)(HANDLE, DWORD, DWORD, LPDWORD, LPDWORD, LPVOID *);
typedef WINBASEAPI BOOL (WINAPI *BackupWriteFunction)(HANDLE, LPBYTE, DWORD, LPDWORD, BOOL, BOOL, LPVOID *);
typedef WINBASEAPI BOOL (WINAPI *CancelIoFunction)(HANDLE);
typedef WINBASEAPI BOOL (WINAPI *CloseHandleFunction)(HANDLE);
typedef WINBASEAPI LPVOID (WINAPI *CreateFiberFunction)(SIZE_T, LPFIBER_START_ROUTINE, LPVOID);
typedef WINBASEAPI LPVOID (WINAPI *CreateFiberExFunction)(SIZE_T, SIZE_T, DWORD, LPFIBER_START_ROUTINE, LPVOID);
typedef WINBASEAPI HANDLE (WINAPI *CreateFileMappingAFunction)(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR);
typedef WINBASEAPI HANDLE (WINAPI *CreateFileMappingWFunction)(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCWSTR);
typedef WINBASEAPI BOOL (WINAPI *CreateHardLinkAFunction)(LPCSTR, LPCSTR, LPSECURITY_ATTRIBUTES);
typedef WINBASEAPI BOOL (WINAPI *CreateHardLinkWFunction)(LPCWSTR, LPCWSTR, LPSECURITY_ATTRIBUTES);
typedef WINBASEAPI HANDLE (WINAPI *CreateMemoryResourceNotificationFunction)(MEMORY_RESOURCE_NOTIFICATION_TYPE);
typedef WINBASEAPI HANDLE (WINAPI *CreateThreadFunction)(LPSECURITY_ATTRIBUTES, SIZE_T, LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
typedef WINBASEAPI HANDLE (WINAPI *CreateToolhelp32SnapshotFunction)(DWORD, DWORD);
typedef WINBASEAPI BOOL (WINAPI *ContinueDebugEventFunction)(DWORD, DWORD, DWORD);
typedef WINBASEAPI BOOL (WINAPI *DebugActiveProcessFunction)(DWORD);
typedef WINBASEAPI BOOL (WINAPI *DebugActiveProcessStopFunction)(DWORD);
typedef WINBASEAPI VOID (WINAPI *DebugBreakFunction)();
typedef WINBASEAPI BOOL (WINAPI *DebugBreakProcessFunction)(HANDLE);
typedef WINBASEAPI BOOL (WINAPI *DebugSetProcessKillOnExitFunction)(BOOL);
typedef WINBASEAPI VOID (WINAPI *FatalAppExitAFunction)(UINT, LPCSTR);
typedef WINBASEAPI VOID (WINAPI *FatalAppExitWFunction)(UINT, LPCWSTR);
typedef WINBASEAPI VOID (WINAPI *FatalExitFunction)(int);
typedef WINBASEAPI VOID (WINAPI *DeleteFiberFunction)(LPVOID);
typedef WINBASEAPI BOOL (WINAPI *DisableThreadLibraryCallsFunction)(HMODULE);
typedef WINBASEAPI BOOL (WINAPI *DnsHostnameToComputerNameAFunction)(LPCSTR, LPSTR, LPDWORD);
typedef WINBASEAPI BOOL (WINAPI *DnsHostnameToComputerNameWFunction)(LPCWSTR, LPWSTR, LPDWORD);
typedef WINBASEAPI HANDLE (WINAPI *FindFirstFileAFunction)(LPCSTR, LPWIN32_FIND_DATAA);
typedef WINBASEAPI HANDLE (WINAPI *FindFirstFileWFunction)(LPCWSTR, LPWIN32_FIND_DATAW);
typedef WINBASEAPI HANDLE (WINAPI *FindFirstFileExAFunction)(LPCSTR, FINDEX_INFO_LEVELS, LPVOID, FINDEX_SEARCH_OPS, LPVOID, DWORD);
typedef WINBASEAPI HANDLE (WINAPI *FindFirstFileExWFunction)(LPCWSTR, FINDEX_INFO_LEVELS, LPVOID, FINDEX_SEARCH_OPS, LPVOID, DWORD);
typedef WINBASEAPI BOOL (WINAPI *FindNextFileAFunction)(HANDLE, LPWIN32_FIND_DATAA);
typedef WINBASEAPI BOOL (WINAPI *FindNextFileWFunction)(HANDLE, LPWIN32_FIND_DATAW);
typedef WINBASEAPI DWORD (WINAPI *GetCompressedFileSizeAFunction)(LPCSTR, LPDWORD);
typedef WINBASEAPI DWORD (WINAPI *GetCompressedFileSizeWFunction)(LPCWSTR, LPDWORD);
typedef WINBASEAPI BOOL (WINAPI *GetExitCodeProcessFunction)(HANDLE, LPDWORD);
typedef WINBASEAPI BOOL (WINAPI *GetExitCodeThreadFunction)(HANDLE, LPDWORD);
typedef WINBASEAPI DWORD (WINAPI *GetFullPathNameAFunction)(LPCSTR, DWORD, LPSTR, LPSTR *);
typedef WINBASEAPI DWORD (WINAPI *GetFullPathNameWFunction)(LPCWSTR, DWORD, LPWSTR, LPWSTR *);
typedef WINBASEAPI HANDLE (WINAPI *GetProcessHeapFunction)();
typedef WINBASEAPI DWORD (WINAPI *GetProcessHeapsFunction)(DWORD, PHANDLE);
typedef WINBASEAPI BOOL (WINAPI *GetProcessIoCountersFunction)(HANDLE, PIO_COUNTERS);
typedef WINBASEAPI BOOL (WINAPI *GetProcessTimesFunction)(HANDLE, LPFILETIME, LPFILETIME, LPFILETIME, LPFILETIME);
typedef WINBASEAPI BOOL (WINAPI *GetProcessWorkingSetSizeFunction)(HANDLE, PSIZE_T, PSIZE_T);
typedef WINBASEAPI VOID (WINAPI *GetStartupInfoAFunction)(LPSTARTUPINFOA);
typedef WINBASEAPI VOID (WINAPI *GetStartupInfoWFunction)(LPSTARTUPINFOW);
typedef WINBASEAPI UINT (WINAPI *GetSystemDirectoryAFunction)(LPSTR, UINT);
typedef WINBASEAPI UINT (WINAPI *GetSystemDirectoryWFunction)(LPWSTR, UINT);
typedef WINBASEAPI UINT (WINAPI *GetSystemWindowsDirectoryAFunction)(LPSTR, UINT);
typedef WINBASEAPI UINT (WINAPI *GetSystemWindowsDirectoryWFunction)(LPWSTR, UINT);
typedef WINBASEAPI UINT (WINAPI *GetWriteWatchFunction)(DWORD, PVOID, SIZE_T, PVOID *, PULONG_PTR, PULONG);
typedef WINBASEAPI VOID (WINAPI *GlobalMemoryStatusFunction)(LPMEMORYSTATUS);
typedef WINBASEAPI HGLOBAL (WINAPI *GlobalReAllocFunction)(HGLOBAL, SIZE_T, UINT);
typedef WINBASEAPI BOOL (WINAPI *LockFileFunction)(HANDLE, DWORD, DWORD, DWORD, DWORD);
typedef WINBASEAPI BOOL (WINAPI *LockFileExFunction)(HANDLE, DWORD, DWORD, DWORD, DWORD, LPOVERLAPPED);
typedef VOID (APIENTRY *LZCloseFunction)(INT);
typedef VOID (APIENTRY *LZCopyFunction)(INT, INT);
typedef INT (APIENTRY *LZOpenFileAFunction)(LPSTR, LPOFSTRUCT, WORD);
typedef INT (APIENTRY *LZOpenFileWFunction)(LPWSTR, LPOFSTRUCT, WORD);
typedef INT (APIENTRY *LZReadFunction)(INT, LPSTR, INT);
typedef LONG (APIENTRY *LZSeekFunction)(INT, LONG, INT);
typedef WINBASEAPI DWORD (WINAPI *LoadModuleFunction)(LPCSTR, LPVOID);
typedef WINBASEAPI HFILE (WINAPI *OpenFileFunction)(LPCSTR, LPOFSTRUCT, UINT);
typedef WINBASEAPI BOOL (WINAPI *QueryMemoryResourceNotificationFunction)(HANDLE, PBOOL);
typedef WINBASEAPI VOID (WINAPI *SetFileApisToANSIFunction)();
typedef WINBASEAPI VOID (WINAPI *SetFileApisToOEMFunction)();
typedef WINBASEAPI DWORD (WINAPI *SetFilePointerFunction)(HANDLE, LONG, PLONG, DWORD);
typedef WINBASEAPI BOOL (WINAPI *SetFilePointerExFunction)(HANDLE, LARGE_INTEGER, PLARGE_INTEGER, DWORD);
typedef WINBASEAPI BOOL (WINAPI *SetFileShortNameAFunction)(HANDLE, LPCSTR);
typedef WINBASEAPI BOOL (WINAPI *SetFileShortNameWFunction)(HANDLE, LPCWSTR);
typedef WINBASEAPI BOOL (WINAPI *SetFileValidDataFunction)(HANDLE, LONGLONG);
typedef WINBASEAPI BOOL (WINAPI *SetEndOfFileFunction)(HANDLE);
typedef WINBASEAPI BOOL (WINAPI *SetPriorityClassFunction)(HANDLE, DWORD);
typedef WINBASEAPI BOOL (WINAPI *SetProcessShutdownParametersFunction)(DWORD, DWORD);
typedef WINBASEAPI BOOL (WINAPI *SetProcessWorkingSetSizeFunction)(HANDLE, SIZE_T, SIZE_T);
typedef WINBASEAPI BOOL (WINAPI *TerminateProcessFunction)(HANDLE, UINT);
typedef WINBASEAPI BOOL (WINAPI *TerminateThreadFunction)(HANDLE, DWORD);
typedef WINBASEAPI DWORD (WINAPI *TlsAllocFunction)();
typedef WINBASEAPI BOOL (WINAPI *TlsFreeFunction)(DWORD);
typedef WINBASEAPI BOOL (WINAPI *UnlockFileFunction)(HANDLE, DWORD, DWORD, DWORD, DWORD);
typedef WINBASEAPI BOOL (WINAPI *UnlockFileExFunction)(HANDLE, DWORD, DWORD, DWORD, LPOVERLAPPED);
typedef WINBASEAPI BOOL (WINAPI *VirtualProtectFunction)(LPVOID, SIZE_T, DWORD, PDWORD);
typedef WINBASEAPI BOOL (WINAPI *VirtualProtectExFunction)(HANDLE, LPVOID, SIZE_T, DWORD, PDWORD);
typedef WINBASEAPI BOOL (WINAPI *WriteProcessMemoryFunction)(HANDLE, LPVOID, LPCVOID, SIZE_T, SIZE_T *);
typedef WINBASEAPI LONG (WINAPI *CompareFileTimeFunction)(CONST FILETIME *, CONST FILETIME *);
typedef WINBASEAPI BOOL (WINAPI *DosDateTimeToFileTimeFunction)(WORD, WORD, LPFILETIME);
typedef WINBASEAPI BOOL (WINAPI *FileTimeToDosDateTimeFunction)(CONST FILETIME *, LPWORD, LPWORD);
typedef WINBASEAPI BOOL (WINAPI *FileTimeToLocalFileTimeFunction)(CONST FILETIME *, LPFILETIME);
typedef WINBASEAPI BOOL (WINAPI *FileTimeToSystemTimeFunction)(CONST FILETIME *, LPSYSTEMTIME);
typedef WINBASEAPI BOOL (WINAPI *GetFileTimeFunction)(HANDLE, LPFILETIME, LPFILETIME, LPFILETIME);
typedef WINBASEAPI VOID (WINAPI *GetLocalTimeFunction)(LPSYSTEMTIME);
typedef WINBASEAPI VOID (WINAPI *GetSystemTimeFunction)(LPSYSTEMTIME);
typedef WINBASEAPI BOOL (WINAPI *GetSystemTimeAdjustmentFunction)(PDWORD, PDWORD, PBOOL);
typedef WINBASEAPI VOID (WINAPI *GetSystemTimeAsFileTimeFunction)(LPFILETIME);
typedef WINBASEAPI int (WINAPI *GetTimeFormatAFunction)(LCID, DWORD, CONST SYSTEMTIME *, LPCSTR, LPSTR, int);
typedef WINBASEAPI int (WINAPI *GetTimeFormatWFunction)(LCID, DWORD, CONST SYSTEMTIME *, LPCWSTR, LPWSTR, int);
typedef WINBASEAPI DWORD (WINAPI *GetTimeZoneInformationFunction)(LPTIME_ZONE_INFORMATION);
typedef WINBASEAPI BOOL (WINAPI *LocalFileTimeToFileTimeFunction)(CONST FILETIME *, LPFILETIME);
typedef WINBASEAPI BOOL (WINAPI *SetFileTimeFunction)(HANDLE, CONST FILETIME *, CONST FILETIME *, CONST FILETIME *);
typedef WINBASEAPI BOOL (WINAPI *SetLocalTimeFunction)(CONST SYSTEMTIME *);
typedef WINBASEAPI BOOL (WINAPI *SetSystemTimeFunction)(CONST SYSTEMTIME *);
typedef WINBASEAPI BOOL (WINAPI *SetSystemTimeAdjustmentFunction)(DWORD, BOOL);
typedef WINBASEAPI BOOL (WINAPI *SetTimeZoneInformationFunction)(CONST TIME_ZONE_INFORMATION *);
typedef WINBASEAPI BOOL (WINAPI *SystemTimeToFileTimeFunction)(CONST SYSTEMTIME *, LPFILETIME);
typedef WINBASEAPI BOOL (WINAPI *SystemTimeToTzSpecificLocalTimeFunction)(LPTIME_ZONE_INFORMATION, LPSYSTEMTIME, LPSYSTEMTIME);
typedef WINBASEAPI BOOL (WINAPI *TzSpecificLocalTimeToSystemTimeFunction)(LPTIME_ZONE_INFORMATION, LPSYSTEMTIME, LPSYSTEMTIME);
typedef WINBASEAPI BOOL (WINAPI *QueryPerformanceCounterFunction)(LARGE_INTEGER *);
typedef WINBASEAPI BOOL (WINAPI *QueryPerformanceFrequencyFunction)(LARGE_INTEGER *);
typedef WINBASEAPI FARPROC (WINAPI *GetProcAddressFunction)(HMODULE, LPCSTR);
typedef WINBASEAPI HMODULE (WINAPI *GetModuleHandleAFunction)(LPCSTR);
typedef WINBASEAPI HMODULE (WINAPI *GetModuleHandleWFunction)(LPCWSTR);
typedef WINBASEAPI BOOL (WINAPI *DeviceIoControlFunction)(HANDLE, DWORD, LPVOID, DWORD, LPVOID, DWORD, LPDWORD, LPOVERLAPPED);
typedef WINBASEAPI BOOL (WINAPI *GetVersionExAFunction)(LPOSVERSIONINFOA);
typedef WINBASEAPI BOOL (WINAPI *GetVersionExWFunction)(LPOSVERSIONINFOW);
typedef WINBASEAPI VOID (WINAPI *GetSystemInfoFunction)(LPSYSTEM_INFO);
typedef WINBASEAPI BOOL (WINAPI *GetVolumeInformationAFunction)(LPCSTR, LPSTR, DWORD, LPDWORD, LPDWORD, LPDWORD, LPSTR, DWORD);
typedef WINBASEAPI BOOL (WINAPI *GetVolumeInformationWFunction)(LPCWSTR, LPWSTR, DWORD, LPDWORD, LPDWORD, LPDWORD, LPWSTR, DWORD);
typedef WINBASEAPI HANDLE (WINAPI *CreateRemoteThreadFunction)(HANDLE, LPSECURITY_ATTRIBUTES, SIZE_T, LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
typedef WINBASEAPI LPSTR (WINAPI *lstrcpyAFunction)(LPSTR, LPSTR);
typedef WINBASEAPI LPSTR (WINAPI *lstrcatAFunction)(LPSTR, LPSTR);
typedef WINBASEAPI LPSTR (WINAPI *lstrcpynAFunction)(LPSTR, LPCSTR, int);
typedef WINBASEAPI int (WINAPI *MultiByteToWideCharFunction)(UINT, DWORD, LPCSTR, int, LPWSTR, int);
typedef WINBASEAPI UINT (WINAPI *WinExecFunction)(LPCSTR, UINT);
typedef WINBASEAPI VOID (WINAPI *InitializeCriticalSectionFunction)(LPCRITICAL_SECTION);
typedef WINBASEAPI VOID (WINAPI *EnterCriticalSectionFunction)(LPCRITICAL_SECTION);
typedef WINBASEAPI LPWSTR (WINAPI *lstrcpyWFunction)(LPWSTR, LPWSTR);
typedef WINBASEAPI LPWSTR (WINAPI *lstrcatWFunction)(LPWSTR, LPWSTR);
typedef WINBASEAPI LPWSTR (WINAPI *lstrcpynWFunction)(LPWSTR, LPCWSTR, int);
typedef WINBASEAPI void (WINAPI *LeaveCriticalSectionFunction)(LPCRITICAL_SECTION);
typedef WINBASEAPI void (WINAPI *DeleteCriticalSectionFunction)(LPCRITICAL_SECTION);
typedef WINBASEAPI HANDLE (WINAPI *CreateIoCompletionPortFunction)(HANDLE, HANDLE, ULONG_PTR, DWORD);
typedef WINBASEAPI BOOL (WINAPI *GetQueuedCompletionStatusFunction)(HANDLE, LPDWORD, PULONG_PTR, LPOVERLAPPED *, DWORD);
typedef WINBASEAPI BOOL (WINAPI *PostQueuedCompletionStatusFunction)(HANDLE, DWORD, ULONG_PTR, LPOVERLAPPED);

// original function pointers
AllocateUserPhysicalPagesFunction realAllocateUserPhysicalPages = NULL;
CopyFileAFunction realCopyFileA = NULL;
CopyFileExAFunction realCopyFileExA = NULL;
CopyFileExWFunction realCopyFileExW = NULL;
CopyFileWFunction realCopyFileW = NULL;
CreateDirectoryAFunction realCreateDirectoryA = NULL;
CreateDirectoryExAFunction realCreateDirectoryExA = NULL;
CreateDirectoryExWFunction realCreateDirectoryExW = NULL;
CreateDirectoryWFunction realCreateDirectoryW = NULL;
CreateFileAFunction realCreateFileA = NULL;
CreateFileWFunction realCreateFileW = NULL;
CreateProcessAFunction realCreateProcessA = NULL;
CreateProcessWFunction realCreateProcessW = NULL;
DeleteFileAFunction realDeleteFileA = NULL;
DeleteFileWFunction realDeleteFileW = NULL;
FlushFileBuffersFunction realFlushFileBuffers = NULL;
FreeLibraryFunction realFreeLibrary = NULL;
FreeLibraryAndExitThreadFunction realFreeLibraryAndExitThread = NULL;
FreeUserPhysicalPagesFunction realFreeUserPhysicalPages = NULL;
GetBinaryTypeAFunction realGetBinaryTypeA = NULL;
GetBinaryTypeWFunction realGetBinaryTypeW = NULL;
GetCurrentDirectoryAFunction realGetCurrentDirectoryA = NULL;
GetCurrentDirectoryWFunction realGetCurrentDirectoryW = NULL;
GetDiskFreeSpaceAFunction realGetDiskFreeSpaceA = NULL;
GetDiskFreeSpaceExAFunction realGetDiskFreeSpaceExA = NULL;
GetDiskFreeSpaceExWFunction realGetDiskFreeSpaceExW = NULL;
GetDiskFreeSpaceWFunction realGetDiskFreeSpaceW = NULL;
GetDriveTypeAFunction realGetDriveTypeA = NULL;
GetDriveTypeWFunction realGetDriveTypeW = NULL;
GetFileAttributesAFunction realGetFileAttributesA = NULL;
GetFileAttributesExAFunction realGetFileAttributesExA = NULL;
GetFileAttributesExWFunction realGetFileAttributesExW = NULL;
GetFileAttributesWFunction realGetFileAttributesW = NULL;
GetFileInformationByHandleFunction realGetFileInformationByHandle = NULL;
GetFileSizeFunction realGetFileSize = NULL;
GetFileSizeExFunction realGetFileSizeEx = NULL;
GetFileTypeFunction realGetFileType = NULL;
GetLogicalDrivesFunction realGetLogicalDrives = NULL;
GetLogicalDriveStringsAFunction realGetLogicalDriveStringsA = NULL;
GetLogicalDriveStringsWFunction realGetLogicalDriveStringsW = NULL;
GlobalAllocFunction realGlobalAlloc = NULL;
GlobalFreeFunction realGlobalFree = NULL;
GlobalMemoryStatusExFunction realGlobalMemoryStatusEx = NULL;
HeapAllocFunction realHeapAlloc = NULL;
HeapCompactFunction realHeapCompact = NULL;
HeapCreateFunction realHeapCreate = NULL;
HeapDestroyFunction realHeapDestroy = NULL;
HeapFreeFunction realHeapFree = NULL;
HeapLockFunction realHeapLock = NULL;
HeapReAllocFunction realHeapReAlloc = NULL;
HeapSizeFunction realHeapSize = NULL;
HeapUnlockFunction realHeapUnlock = NULL;
HeapValidateFunction realHeapValidate = NULL;
LoadLibraryAFunction realLoadLibraryA = NULL;
LoadLibraryExAFunction realLoadLibraryExA = NULL;
LoadLibraryExWFunction realLoadLibraryExW = NULL;
LoadLibraryWFunction realLoadLibraryW = NULL;
LocalAllocFunction realLocalAlloc = NULL;
LocalFreeFunction realLocalFree = NULL;
LocalReAllocFunction realLocalReAlloc = NULL;
MapUserPhysicalPagesFunction realMapUserPhysicalPages = NULL;
MapUserPhysicalPagesScatterFunction realMapUserPhysicalPagesScatter = NULL;
MapViewOfFileFunction realMapViewOfFile = NULL;
MapViewOfFileExFunction realMapViewOfFileEx = NULL;
MoveFileAFunction realMoveFileA = NULL;
MoveFileExAFunction realMoveFileExA = NULL;
MoveFileExWFunction realMoveFileExW = NULL;
MoveFileWFunction realMoveFileW = NULL;
MoveFileWithProgressAFunction realMoveFileWithProgressA = NULL;
MoveFileWithProgressWFunction realMoveFileWithProgressW = NULL;
ReadFileFunction realReadFile = NULL;
ReadFileExFunction realReadFileEx = NULL;
ReadFileScatterFunction realReadFileScatter = NULL;
RemoveDirectoryAFunction realRemoveDirectoryA = NULL;
RemoveDirectoryWFunction realRemoveDirectoryW = NULL;
ReplaceFileAFunction realReplaceFileA = NULL;
ReplaceFileWFunction realReplaceFileW = NULL;
SearchPathAFunction realSearchPathA = NULL;
SearchPathWFunction realSearchPathW = NULL;
SetFileAttributesAFunction realSetFileAttributesA = NULL;
SetFileAttributesWFunction realSetFileAttributesW = NULL;
VirtualAllocFunction realVirtualAlloc = NULL;
VirtualAllocExFunction realVirtualAllocEx = NULL;
VirtualFreeFunction realVirtualFree = NULL;
VirtualFreeExFunction realVirtualFreeEx = NULL;
VirtualLockFunction realVirtualLock = NULL;
VirtualQueryFunction realVirtualQuery = NULL;
VirtualQueryExFunction realVirtualQueryEx = NULL;
VirtualUnlockFunction realVirtualUnlock = NULL;
WriteFileFunction realWriteFile = NULL;
WriteFileExFunction realWriteFileEx = NULL;
WriteFileGatherFunction realWriteFileGather = NULL;
AllocConsoleFunction realAllocConsole = NULL;
AreFileApisANSIFunction realAreFileApisANSI = NULL;
AttachConsoleFunction realAttachConsole = NULL;
BackupReadFunction realBackupRead = NULL;
BackupSeekFunction realBackupSeek = NULL;
BackupWriteFunction realBackupWrite = NULL;
CancelIoFunction realCancelIo = NULL;
CloseHandleFunction realCloseHandle = NULL;
CreateFiberFunction realCreateFiber = NULL;
CreateFiberExFunction realCreateFiberEx = NULL;
CreateFileMappingAFunction realCreateFileMappingA = NULL;
CreateFileMappingWFunction realCreateFileMappingW = NULL;
CreateHardLinkAFunction realCreateHardLinkA = NULL;
CreateHardLinkWFunction realCreateHardLinkW = NULL;
CreateMemoryResourceNotificationFunction realCreateMemoryResourceNotification = NULL;
CreateThreadFunction realCreateThread = NULL;
CreateToolhelp32SnapshotFunction realCreateToolhelp32Snapshot = NULL;
ContinueDebugEventFunction realContinueDebugEvent = NULL;
DebugActiveProcessFunction realDebugActiveProcess = NULL;
DebugActiveProcessStopFunction realDebugActiveProcessStop = NULL;
DebugBreakFunction realDebugBreak = NULL;
DebugBreakProcessFunction realDebugBreakProcess = NULL;
DebugSetProcessKillOnExitFunction realDebugSetProcessKillOnExit = NULL;
FatalAppExitAFunction realFatalAppExitA = NULL;
FatalAppExitWFunction realFatalAppExitW = NULL;
FatalExitFunction realFatalExit = NULL;
DeleteFiberFunction realDeleteFiber = NULL;
DisableThreadLibraryCallsFunction realDisableThreadLibraryCalls = NULL;
DnsHostnameToComputerNameAFunction realDnsHostnameToComputerNameA = NULL;
DnsHostnameToComputerNameWFunction realDnsHostnameToComputerNameW = NULL;
FindFirstFileAFunction realFindFirstFileA = NULL;
FindFirstFileWFunction realFindFirstFileW = NULL;
FindFirstFileExAFunction realFindFirstFileExA = NULL;
FindFirstFileExWFunction realFindFirstFileExW = NULL;
FindNextFileAFunction realFindNextFileA = NULL;
FindNextFileWFunction realFindNextFileW = NULL;
GetCompressedFileSizeAFunction realGetCompressedFileSizeA = NULL;
GetCompressedFileSizeWFunction realGetCompressedFileSizeW = NULL;
GetExitCodeProcessFunction realGetExitCodeProcess = NULL;
GetExitCodeThreadFunction realGetExitCodeThread = NULL;
GetFullPathNameAFunction realGetFullPathNameA = NULL;
GetFullPathNameWFunction realGetFullPathNameW = NULL;
GetProcessHeapFunction realGetProcessHeap = NULL;
GetProcessHeapsFunction realGetProcessHeaps = NULL;
GetProcessIoCountersFunction realGetProcessIoCounters = NULL;
GetProcessTimesFunction realGetProcessTimes = NULL;
GetProcessWorkingSetSizeFunction realGetProcessWorkingSetSize = NULL;
GetStartupInfoAFunction realGetStartupInfoA = NULL;
GetStartupInfoWFunction realGetStartupInfoW = NULL;
GetSystemDirectoryAFunction realGetSystemDirectoryA = NULL;
GetSystemDirectoryWFunction realGetSystemDirectoryW = NULL;
GetSystemWindowsDirectoryAFunction realGetSystemWindowsDirectoryA = NULL;
GetSystemWindowsDirectoryWFunction realGetSystemWindowsDirectoryW = NULL;
GetWriteWatchFunction realGetWriteWatch = NULL;
GlobalMemoryStatusFunction realGlobalMemoryStatus = NULL;
GlobalReAllocFunction realGlobalReAlloc = NULL;
LockFileFunction realLockFile = NULL;
LockFileExFunction realLockFileEx = NULL;
LZCloseFunction realLZClose = NULL;
LZCopyFunction realLZCopy = NULL;
LZOpenFileAFunction realLZOpenFileA = NULL;
LZOpenFileWFunction realLZOpenFileW = NULL;
LZReadFunction realLZRead = NULL;
LZSeekFunction realLZSeek = NULL;
LoadModuleFunction realLoadModule = NULL;
OpenFileFunction realOpenFile = NULL;
QueryMemoryResourceNotificationFunction realQueryMemoryResourceNotification = NULL;
SetFileApisToANSIFunction realSetFileApisToANSI = NULL;
SetFileApisToOEMFunction realSetFileApisToOEM = NULL;
SetFilePointerFunction realSetFilePointer = NULL;
SetFilePointerExFunction realSetFilePointerEx = NULL;
SetFileShortNameAFunction realSetFileShortNameA = NULL;
SetFileShortNameWFunction realSetFileShortNameW = NULL;
SetFileValidDataFunction realSetFileValidData = NULL;
SetEndOfFileFunction realSetEndOfFile = NULL;
SetPriorityClassFunction realSetPriorityClass = NULL;
SetProcessShutdownParametersFunction realSetProcessShutdownParameters = NULL;
SetProcessWorkingSetSizeFunction realSetProcessWorkingSetSize = NULL;
TerminateProcessFunction realTerminateProcess = NULL;
TerminateThreadFunction realTerminateThread = NULL;
TlsAllocFunction realTlsAlloc = NULL;
TlsFreeFunction realTlsFree = NULL;
UnlockFileFunction realUnlockFile = NULL;
UnlockFileExFunction realUnlockFileEx = NULL;
VirtualProtectFunction realVirtualProtect = NULL;
VirtualProtectExFunction realVirtualProtectEx = NULL;
WriteProcessMemoryFunction realWriteProcessMemory = NULL;
CompareFileTimeFunction realCompareFileTime = NULL;
DosDateTimeToFileTimeFunction realDosDateTimeToFileTime = NULL;
FileTimeToDosDateTimeFunction realFileTimeToDosDateTime = NULL;
FileTimeToLocalFileTimeFunction realFileTimeToLocalFileTime = NULL;
FileTimeToSystemTimeFunction realFileTimeToSystemTime = NULL;
GetFileTimeFunction realGetFileTime = NULL;
GetLocalTimeFunction realGetLocalTime = NULL;
GetSystemTimeFunction realGetSystemTime = NULL;
GetSystemTimeAdjustmentFunction realGetSystemTimeAdjustment = NULL;
GetSystemTimeAsFileTimeFunction realGetSystemTimeAsFileTime = NULL;
GetTimeFormatAFunction realGetTimeFormatA = NULL;
GetTimeFormatWFunction realGetTimeFormatW = NULL;
GetTimeZoneInformationFunction realGetTimeZoneInformation = NULL;
LocalFileTimeToFileTimeFunction realLocalFileTimeToFileTime = NULL;
SetFileTimeFunction realSetFileTime = NULL;
SetLocalTimeFunction realSetLocalTime = NULL;
SetSystemTimeFunction realSetSystemTime = NULL;
SetSystemTimeAdjustmentFunction realSetSystemTimeAdjustment = NULL;
SetTimeZoneInformationFunction realSetTimeZoneInformation = NULL;
SystemTimeToFileTimeFunction realSystemTimeToFileTime = NULL;
SystemTimeToTzSpecificLocalTimeFunction realSystemTimeToTzSpecificLocalTime = NULL;
TzSpecificLocalTimeToSystemTimeFunction realTzSpecificLocalTimeToSystemTime = NULL;
QueryPerformanceCounterFunction realQueryPerformanceCounter = NULL;
QueryPerformanceFrequencyFunction realQueryPerformanceFrequency = NULL;
GetProcAddressFunction realGetProcAddress = NULL;
GetModuleHandleAFunction realGetModuleHandleA = NULL;
GetModuleHandleWFunction realGetModuleHandleW = NULL;
DeviceIoControlFunction realDeviceIoControl = NULL;
GetVersionExAFunction realGetVersionExA = NULL;
GetVersionExWFunction realGetVersionExW = NULL;
GetSystemInfoFunction realGetSystemInfo = NULL;
GetVolumeInformationAFunction realGetVolumeInformationA = NULL;
GetVolumeInformationWFunction realGetVolumeInformationW = NULL;
CreateRemoteThreadFunction realCreateRemoteThread = NULL;
lstrcpyAFunction reallstrcpyA = NULL;
lstrcatAFunction reallstrcatA = NULL;
lstrcpynAFunction reallstrcpynA = NULL;
MultiByteToWideCharFunction realMultiByteToWideChar = NULL;
WinExecFunction realWinExec = NULL;
InitializeCriticalSectionFunction realInitializeCriticalSection = NULL;
EnterCriticalSectionFunction realEnterCriticalSection = NULL;
lstrcpyWFunction reallstrcpyW = NULL;
lstrcatWFunction reallstrcatW = NULL;
lstrcpynWFunction reallstrcpynW = NULL;
LeaveCriticalSectionFunction realLeaveCriticalSection = NULL;
DeleteCriticalSectionFunction realDeleteCriticalSection = NULL;
CreateIoCompletionPortFunction realCreateIoCompletionPort = NULL;
GetQueuedCompletionStatusFunction realGetQueuedCompletionStatus = NULL;
PostQueuedCompletionStatusFunction realPostQueuedCompletionStatus = NULL;

ReplacementLibrary *library = NULL;
LogSender *logSender = NULL;
Mutex *createProcessMutex = NULL;
Event *childProcessCreatedEvent = NULL;
Event *holodeckAttachedToChildProcessEvent = NULL;
MemoryMappedFile *childProcessDataFile = NULL;
