//*************************************************************************
// Copyright (C) Security Innovation, LLC, 2002-2003 – All Rights Reserved.
//
// FILE:		defines.h
//
// DESCRIPTION: Contains common defines for Holodeck used in multiple modules
//
//=========================================================================
// Modification History
//
// Date         SCR  Name        Purpose
// -----------  ---  ----------- ------------------------------------------
// 30 DEC 2002		 B. Shirey	 File created.
//*************************************************************************
#pragma once

#define MAX_TRIAL_LOG_ENTRIES		100
#define ROOT_KEY					HKEY_LOCAL_MACHINE
#define INSTALLED_ROOT_KEY			HKEY_LOCAL_MACHINE
#define ROOT_PATH					"Software\\Security Innovation\\Holodeck Enterprise Edition"
#define DOTNET_REPLACEMENT_DLLS_KEY	"DotNetReplacementDlls"
#define LOG_VERSION_STRING			"HDV2_5"
#define LOG_PIPE_VALUE_NAME			"LogPipeName"
#define TEST_SETTINGS_KEY			"TestSettings"
#define DOTNET_LIBS_INIT_LIST_KEY	"DotNetLibsInitList"
#define DISABLE_LOGGING_KEY			"Disabled Logging List"
#define DISABLE_LOGGING_VALUE		"DisableAll"
#define MAIN_FRAME_STATE_KEY		"AppState"
#define INSTALL_PATH_VALUE_NAME		"InstallPath"
#define PANE_SETTINGS_VALUE_NAME	"PaneSettings"
#define PANE_VISIBLE_VALUE_NAME		"Displayed"
#define SERIAL_NUMBER_VALUE_NAME	"SerialNumber"
#define REGISTRATION_KEY_VALUE_NAME	"RegistrationKey"
#define FUNCTION_DB_PATH_VALUE_NAME	"FunctionDatabaseFolder"
#define TOOLS_PATH_VALUE_NAME		"ToolsFolder"
#define LIB_EXPORT_PATH_VALUE_NAME	"LibraryExportPath"
#define NEWINTERCEPTS_TPL_PATH_NAME "NewInterceptsTemplatePath"
#define PLUGIN_DLL_PATH_VALUE_NAME	"ReplacementLibraryFolder"
#define LOG_PATH_VALUE_NAME			"LogFolder"
#define DOT_NET_CACHE_PATH_VALUE	"DotNetCacheFolder"
#define DTD_PATH_VALUE_NAME			"DtdPath"
#define PROCESS_CHAINING_VALUE_NAME	"ProcessChaining"
#define USAGE_REG_KEY_NAME			"Usage"
#define FUNCTION_CALL_COUNT_VALUE_NAME	"CallCount"
#define TEST_EXECUTE_COUNT_VALUE_NAME	"TestExecuteCount"
#define MAX_DISK_USAGE_VALUE_NAME	"MaxDiskUsage"
#define CURR_DISK_USAGE_VALUE_NAME	"CurrentDiskUsage"
#define MAX_MEM_USAGE_VALUE_NAME	"MaxMemoryUsage"
#define CURR_MEM_USAGE_VALUE_NAME	"CurrentMemoryUsage"
#define NETWORK_ULOADBW_VALUE_NAME  "UploadBandwidth"
#define NETWORK_DLOADBW_VALUE_NAME  "DownloadBandwidth"
#define TOTAL_BYTES_SENT_VALUE_NAME "TotalBytesSent"
#define TOTAL_BYTES_RECV_VALUE_NAME "TotalBytesReceived"
#define NETWORK_RECVSTMP_VALUE_NAME "NetworkLastReceiveStamp"
#define NETWORK_SENDSTMP_VALUE_NAME "NetworkLastSendStamp"
#define CHECK_RESOURCE_PARAM_VALUE_NAME		"ParamIndex"
#define CHECK_RESOURCE_EXISTS_VALUE_NAME	"Exists"
#define FAULTS_KEY_NAME				"Faults"
#define PANES_KEY_NAME				"Panes"
#define NATIVE_USER_FILENAME_DB_PREFIX	"native_"
#define DOTNET_USER_FILENAME_DB_PREFIX	"dotnet_"
#define FUNCTION_DB_FILE_NAME		"functions.xml"
#define DOT_NET_FUNC_DB_FILE_NAME	"DotNetFunctions.xml"
#define PANE_SETTINGS_DATA_FILE_NAME "paneSettings.dat"
#define FAULT_DB_FILE_NAME			"faults.xml"
#define ERROR_CODE_DB_FILE_NAME		"ErrorCodes.xml"
#define EXCEPTION_DB_FILE_NAME		"Exceptions.xml"
#define PORT_DB_FILE_NAME			"Ports.xml"
#define SEND_LOG_WAIT_TIME			100
#define RECEIVE_LOG_WAIT_TIME		100
#define LOG_SENT_EVENT_NAME_PREFIX	"HolodeckLogsSent_"
#define NOTIFIER_DONE_EVENT_PREFIX	"HolodeckLogsReceived_"
#define LOG_SENT_MAP_FILE_PREFIX	"HolodeckMMFile_"
#define LOG_FILE_MUTEX_PREFIX		"HolodeckLogAccess_"
#define CHILD_PROCESS_EVENT_PREFIX	"HolodeckChildProcCreated_"
#define HOLODECK_ATTACHED_PREFIX	"HolodeckAttachedToNewChild_"
#define CHILD_PROC_MAP_FILE_PREFIX	"HolodeckChildProcDataFile_"
#define FORCE_WRITE_MUTEX_PREFIX	"HolodeckLogWrite_"
#define HEAT_INJECT_DONE_PREFIX		"HEATInjectionDone_"
#define CANT_CREATE_LOG_FILE_PREFIX	"HolodeckCantCreateLogFile_"
#define PAUSE_EVENT_NAME_PREFIX		"HolodeckTestPaused_"
#define LOG_TRUE_DISPLAY_STRING		"True"
#define LOG_FALSE_DISPLAY_STRING	"False"
#define HEAT_DLL_FILE_NAME			"Heat4Dll.dll"
#define DISABLE_INTERCEPT_FUNC_NAME	"disableInterceptionInCurrentThread"
#define ENABLE_INTERCEPT_FUNC_NAME	"enableInterceptionInCurrentThread"
#define GET_CALL_LEVEL_FUNC_NAME	"getCallLevel"
#define INC_CALL_LEVEL_FUNC_NAME	"incrementCallLevel"
#define DEC_CALL_LEVEL_FUNC_NAME	"decrementCallLevel"
#define ORIGINAL_CALLER_FUNC_NAME	"getOriginalFunctionCaller"
#define CREATE_THREAD_FUNC_NAME		"HeatCreateThread"
#define IS_CREATED_THREAD_FUNC_NAME	"IsHeatCreatedThread"
// 60 seconds in 1 millisecond intervals
#define WAIT_FOR_SERVICE_TIMEOUT	60000
#define WAIT_FOR_THREAD_JOIN_TIMEOUT 1000
#define SERVICE_GROUP_KEY_NAME		"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\SvcHost"
#define SERVICES_BASE_KEY_NAME		"SYSTEM\\CurrentControlSet\\Services"
#define IMAGE_PATH_VALUE_NAME		"ImagePath"
#define MAX_PARAMETER_COLUMNS		12
#define MAX_VISIBLE_LOG_ENTRIES		100
#define MAX_LOG_QUEUE_SIZE			1024
#define LOG_FOLDER_DEFAULT_VALUE	"\\Logs"
#define REPORT_FOLDER_DEFAULT_VALUE	"\\Reports"
#define REPORT_FILE_NAME			"Holodeck Report.htm"
#define LOGS_XML_FILE_NAME			"\\Holodeck Report_files\\Logs.xml"
#define FAULTS_XML_FILE_NAME		"\\Holodeck Report_files\\Faults.xml"
#define TESTS_XML_FILE_NAME			"\\Holodeck Report_files\\Tests.xml"
#define PARAMS_XML_FILE_NAME		"\\Holodeck Report_files\\Param Values.xml"
#define RESOURCES_XML_FILE_NAME		"\\Holodeck Report_files\\Resource Dependencies.xml"
#define USAGES_XML_FILE_NAME		"\\Holodeck Report_files\\Resource Usages.xml"
#define ICON_FILE_NAME				"images\\app.ico"
#define GLOBAL_THREAD_NAME			"Common"
#define RECORDED_SESSION_FOLDER		"\\Recorded Sessions"
#define RECORDED_SESSION_FILE		"\\Recorded Session.xml"
#define TESTGEN_SETTINGS_FILE       "\\Test Generation\\TestGeneration.xml"
#define ERROR_LOG_FILE				"ErrorLog.txt"
#define NET_CORRUPT_KEY_NAME		"NetworkCorruption"
#define NET_CORRUPT_RECV_VALUE		"Recv"
#define NET_CORRUPT_SEND_VALUE		"Send"
#define NET_CORRUPT_PORT_MASK		"PortMask"
#define NET_CORRUPT_MODIFY_EXPR		"Expr"
#define FILE_CORRUPT_KEY_NAME		"FileCorruption"
#define FILE_CORRUPT_ORIG_FILE		"OrigFile"
#define FILE_CORRUPT_REGEN_VALUE	"Regen"
#define FILE_CORRUPT_MODIFY_EXPR	"Expr"
#define FILE_CORRUPT_LAST_FILE		"LastCorruptedFile"
#define FILE_CORRUPT_LAST_CHANGES	"LastCorruptedChanges"
#define REGISTRY_CHANGE_WAIT_TIME	100
#define PROJECT_PATH_VALUE_NAME		"ProjectPath"
#define NEW_THREAD_FLAG				"0"
#define NEW_PROCESS_FLAG			"1"
#define PROCESS_WATCH_WAIT_TIME		100
#define TEST_PAUSE_WATCH_WAIT_TIME	100
//button bar icons
#define NEW_PROJECT_ICON_FILE		"images\\new_project.gif"
#define OPEN_PROJECT_ICON_FILE		"images\\open_project.gif"
#define SAVE_PROJECT_ICON_FILE		"images\\save_project.gif"
#define NEW_TEST_APP_ICON_FILE		"images\\new_test_app.gif"
#define CREATE_TEST_ICON_FILE		"images\\create_test.gif"
#define NEW_FAULT_ICON_FILE			"images\\new_fault.gif"
#define CREATE_REPORT_ICON_FILE		"images\\create_report.gif"
#define PROJECT_PANE_ICON_FILE		"images\\project_pane.gif"
#define RESOURCE_PANE_ICON_FILE		"images\\resource_pane.gif"
#define LIMITS_PANE_ICON_FILE		"images\\limits_pane.gif"
#define FILE_CORRUPT_PANE_ICON_FILE	"images\\file_corrupt_pane.ico"
#define NETWORK_MSG_PANE_ICON_FILE	"images\\network_message_pane.ico"
#define PROPERTIES_PANE_ICON_FILE	"images\\properties_pane.gif"
#define HELP_CONTENTS_ICON_FILE		"images\\help_contents_pane.gif"
#define DYNAMIC_HELP_ICON_FILE		"images\\help_pane.gif"
#define NETWORK_LOG_ICON_FILE		"images\\network_log.gif"
#define HOLODECK_LOGO_FILE			"images\\HolodeckEE.bmp"
//project pane icons
#define PROCESS_ICON_FILE			"images\\Process.ico"
#define THREAD_ICON_FILE			"images\\Thread.ico"
#define RECORDEDSESSIONS_ICON_FILE	"images\\RecordedSessions.ico"
#define RECORDEDSESSION_ICON_FILE	"images\\RecordedSession.ico"
#define REPORTS_ICON_FILE			"images\\Reports.ico"
#define REPORT_ICON_FILE			"images\\Report.ico"
#define LOGS_ICON_FILE				"images\\Logs.ico"
#define NETWORK_LOGS_ICON_FILE		"images\\NetworkLogs.ico"
#define NETWORKLOG_ICON_FILE		"images\\NetworkLog.ico"
#define ACTIVELOG_ICON_FILE			"images\\ActiveLog.ico"
#define SAVEDLOG_ICON_FILE			"images\\SavedLog.ico"
#define RESOURCES_ICON_FILE			"images\\Resources.ico"
#define MEMORY_ICON_FILE			"images\\Memory.ico"
#define DISK_ICON_FILE				"images\\Disk.ico"
#define NETWORK_ICON_FILE			"images\\Network.ico"
#define CUSTOM_ICON_FILE			"images\\Custom.ico"
#define FILES_ICON_FILE				"images\\Files.ico"
#define FILE_ICON_FILE				"images\\File.ico"
#define FILE_CORRUPTION_ICON_FILE	"images\\FileCorruption.ico"
#define REGISTRY_ICON_FILE			"images\\Registry.ico"
#define REGISTRYENTRY_ICON_FILE		"images\\RegistryEntry.ico"
#define RESOURCE_FAULTS_ICON_FILE	"images\\ResourceFaults.ico"
#define REGISTRY_FAULTS_ICON_FILE	"images\\RegistryFaults.ico"
#define PROCESS_FAULTS_ICON_FILE	"images\\ProcessFaults.ico"
#define FAULTS_ICON_FILE			"images\\Faults.ico"
#define FAULT_ICON_FILE				"images\\Fault.ico"
#define LIMITS_ICON_FILE			"images\\Limits.ico"
#define TESTS_ICON_FILE				"images\\Tests.ico"
#define TEST_ICON_FILE				"images\\Test.ico"
#define PAUSED_PROCESS_ICON_FILE	"images\\PausedProcess.ico"
#define TERM_PROCESS_ICON_FILE		"images\\TerminatedProcess.ico"
#define EXCEPTIONS_ICON_FILE		"images\\Exceptions.ico"
#define EXCEPTION_ICON_FILE			"images\\Bug.ico"
// other icons
#define SORT_ASCENDING_ICON_FILE	"images\\sort_ascending.ico"
#define SORT_DESCENDING_ICON_FILE	"images\\sort_descending.ico"
// dynamic help pages
#define BLANK_HTML_FILE						"about:blank"
#define LOGS_DYNAMIC_HELP_FILE				"help\\logpane_dyn.html"
#define FAULTS_DYNAMIC_HELP_FILE			"help\\faultpane_dyn.html"
#define RESOURCES_DYNAMIC_HELP_FILE			"help\\resourcepane_dyn.html"
#define TESTS_DYNAMIC_HELP_FILE				"help\\testspane_dyn.html"
#define PROCESS_DYNAMIC_HELP_FILE			"help\\process_dyn.html"
#define THREAD_DYNAMIC_HELP_FILE			"help\\thread_dyn.html"
#define REPORTS_DYNAMIC_HELP_FILE			"help\\reports_dyn.html"
#define RECORDED_DYNAMIC_HELP_FILE			"help\\recorded_dyn.html"
#define LIMITS_DYNAMIC_HELP_FILE			"help\\limits_dyn.html"
#define NETWORK_DYNAMIC_HELP_FILE			"help\\network_dyn.html"
#define CORRUPTEDFILES_DYNAMIC_HELP_FILE	"help\\corrupted_files_dyn.html"
#define EXCEPTIONS_DYNAMIC_HELP_FILE		"help\\exceptions_dyn.html"
#define FILEFAULTS_DYNAMIC_HELP_FILE		"help\\file_corruption_faults_dyn.html"
#define NETWORKLOGS_DYNAMIC_HELP_FILE		"help\\network_logs_dyn.html"
#define RESOURCEFAULTS_DYNAMIC_HELP_FILE	"help\\resource_faults_dyn.html"

#define TABLE_OF_CONTENTS_HELP_FILE	"help\\hd_help.htm"
#define PDF_HELP_FILE				"help\\hd_help.pdf"
// trial disabled help pages
#define FILE_CORRUPTION_HELP_FILE	"Help\\Holodeck_in_depth\\Generating_File_Corruption\\File_Corruption_Overview.htm"
#define LIBRARY_EXPORTER_HELP_FILE	"Help\\Holodeck_in_depth\\Add_Holodeck_Intercepts\\Add_Holodeck_Intercepts.htm"
#define NEW_TEST_APP_HELP_FILE		"Help\\Holodeck_in_depth\\Multiple_Threads_and_Processes\\Dealing_with_Multiple_Processes.htm"
#define EXPORT_LOG_HELP_FILE		"Help\\Holodeck_in_depth\\Working_with_Logs\\Exporting_Logs_1.htm"
#define CODE_COVERAGE_HELP_FILE		"Help\\Holodeck_in_depth\\Using_Automatic_Test_Generation\\Creating_Code_Coverage_Generation.htm"
#define STRESS_TEST_HELP_FILE		"Help\\Holodeck_in_depth\\Using_Automatic_Test_Generation\\Creating_Stress_Test_Generation.htm"
#define RECORD_SESSION_HELP_FILE	"Help\\Holodeck_in_depth\\Recording_and_replaying_sessions\\Introduction_to_recoding_and_replaying.htm"
#define REPLAY_SESSION_HELP_FILE	"Help\\Holodeck_in_depth\\Recording_and_replaying_sessions\\Replaying_a_recorded_session.htm"
// other help pages used in HD
#define GETTING_STARTED_HELP_FILE	"Help\\Getting_Started\\Getting_started_guide.htm"
#define NAG_SCREEN_HELP_FILE		"Help\\Getting_Started\\Getting_started_guide_trial.htm"
#define CANT_CREATE_LOG_HELP_FILE	"cant_create_log_file.htm"
#define REG_EXPR_HELP_FILE			"Help\\Holodeck_in_depth\\Regular_Expressions_and_Replacement_Strings\\Using_regular_expressions.htm"
#define CUSTOM_FAULTS_HELP_FILE		"Help\\Holodeck_in_depth\\Creating_Faults\\Adding_custom_faults.htm"
#define USING_SYMBOLS_HELP_FILE		"Help\\Holodeck_in_depth\\Creating_Tests\\Creating_a_Test_Based_on_Stack_Matching.htm"
#define LOGGING_OPTIONS_HELP_FILE	"Help\\Holodeck_in_depth\\New_Project_Wizard\\Default_Logging.htm"
// custom filter forms
#define MAX_DISPLAY_ERRORCODES		500
#define MAX_DISPLAY_RETURNVALS		500
// network logging
#define INCOMING_MESSAGE_TEXT		"Recv"
#define OUTGOING_MESSAGE_TEXT		"Send"
// create scheduled test wizard
#define OUT_PARAM_NO_CHANGE_STRING	"No Change"
#define IN_PARAM_MATCH_ANY_STRING	"{Any}"
#define IN_PARAM_MATCH_TRUE_STRING	"{True}"
#define IN_PARAM_MATCH_FALSE_STRING	"{False}"
#define IN_PARAM_MATCH_NULL_STRING	"{NULL}"
#define EQUAL_OPERATOR_TEXT			"Equal To"
#define EQUAL_OPERATOR				"="
#define NOT_EQUAL_OPERATOR_TEXT		"Not Equal To"
#define NOT_EQUAL_OPERATOR			"!="
#define LESS_THAN_OPERATOR_TEXT		"Less Than"
#define LESS_THAN_OPERATOR			"<"
#define GREATER_THAN_OPERATOR_TEXT	"Greater Than"
#define GREATER_THAN_OPERATOR		">"
#define LESS_EQUAL_OPERATOR_TEXT	"Less Than Or Equal To"
#define LESS_EQUAL_OPERATOR			"<="
#define GREATER_EQUAL_OPERATOR_TEXT	"Greater Than Or Equal To"
#define GREATER_EQUAL_OPERATOR		">="
#define STARTS_WITH_OPERATOR_TEXT	"Starts With"
#define STARTS_WITH_OPERATOR		"starts with"
#define ENDS_WITH_OPERATOR_TEXT		"Ends With"
#define ENDS_WITH_OPERATOR			"ends with"
#define SUBSTRING_OPERATOR_TEXT		"Contains Substring"
#define SUBSTRING_OPERATOR			"contains"
#define NOT_CONTAINS_OPERATOR_TEXT	"Doesn't Contain Substring"
#define NOT_CONTAINS_OPERATOR		"not contains"
#define BINARY_CONTAINS_OPERATOR_TEXT		"Contains Binary Value"
#define BINARY_CONTAINS_OPERATOR			"binary contains"
#define BINARY_NOT_CONTAINS_OPERATOR_TEXT	"Doesn't Contain Binary Value"
#define BINARY_NOT_CONTAINS_OPERATOR		"binary not contains"
#define EQUAL_RESOURCE_OPERATOR_TEXT		"Equal to resource path"
#define EQUAL_RESOURCE_OPERATOR				"=resource"
#define NOT_EQUAL_RESOURCE_OPERATOR_TEXT	"Not equal to resource path"
#define NOT_EQUAL_RESOURCE_OPERATOR			"!=resource"
#define CONTAINS_RESOURCE_OPERATOR_TEXT		"Contains resource path"
#define CONTAINS_RESOURCE_OPERATOR			"contains resource"
#define NOT_CONTAINS_RESOURCE_OPERATOR_TEXT	"Doesn't contain resource path"
#define NOT_CONTAINS_RESOURCE_OPERATOR		"not contains resource path"
#define STARTS_WITH_RESOURCE_OPERATOR_TEXT	"Starts with resource path"
#define STARTS_WITH_RESOURCE_OPERATOR		"starts with resource path"

// column header text
#define TIME_STAMP_HEADER_TEXT		"TimeStamp"
#define THREAD_ID_HEADER_TEXT		"Thread"
#define CATEGORY_HEADER_TEXT		"Category"
#define DLL_HEADER_TEXT				"Dll"
#define FUNCTION_HEADER_TEXT		"Function"
#define RETURN_VALUE_HEADER_TEXT	"Return Value"
#define ERROR_CODE_HEADER_TEXT		"Error Code"
#define EXCEPTION_HEADER_TEXT		"Exception"
#define PARAM_HEADER_TEXT_PREFIX	"Parameter "
#define DIRECTION_HEADER_TEXT		"Direction"
#define PROTOCOL_HEADER_TEXT		"Protocol"
#define MSG_LENGTH_HEADER_TEXT		"Msg Length"
#define DESTINATION_IP_HEADER_TEXT	"Destination IP"
#define DESTINATION_PORT_HEADER_TEXT	"Destination Port"
#define SOURCE_IP_HEADER_TEXT		"Source IP"
#define SOURCE_PORT_HEADER_TEXT		"Source Port"
#define MSG_DATA_HEADER_TEXT		"Start of Msg"
#define MSG_OFFSET_HEADER_TEXT		"Msg Offset"
#define MSG_BYTES_HEADER_TEXT		"Modified Hex Data"
#define MSG_ASCII_HEADER_TEXT		"Modified ASCII Data"
#define MSG_ORIGINAL_BYTES_HEADER_TEXT	"Original Hex Data"
#define MSG_ORIGINAL_ASCII_HEADER_TEXT	"Original ASCII Data"
#define HOLODECK_FULL_TITLE_TEXT	"Holodeck Enterprise Edition"
#define HOLODECK_TRIAL_TITLE_TEXT	"Holodeck Enterprise Edition (Trial Version)"

// corruption fault strings
#define RANDOM_CORRUPTION_TEXT		"Random"
#define REG_EXPR_CORRUPTION_TEXT	"RegExpr"
#define REPLACE_CORRUPTION_TEXT		"Replace"
#define RANDOM_SINGLE_BYTE_TEXT		"Random Single Byte"

// max 2 MB corruption files in the rtf box
#define MAX_CORRUPT_DETAILS_FILE_SIZE_TO_DISPLAY	2097152